name: coolint
description: Recommended lints for cool apps, packages, and plugins to encourage good coding practices.

repository: https://github.com/coolosos/coolint
issue_tracker: https://github.com/coolosos/coolint/issues
homepage: https://github.com/coolosos

version: 2.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter_lints: ">=3.0.2 <6.0.0"
